- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Vijaya Reddy, {{ GREETING | default('Good Morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"

  - name: read students yaml
    ansible.builtin.set_fact: # setting the variable
      student_yaml: "{{ lookup('file', 'students.yaml' ) | from_yaml }}"

  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json  }}"